import test from 'node:test';
import assert from 'node:assert/strict';
import {estimateLocally} from '../public/route-timing.js';

test('signed-in delivery route shows next stop, controls, sorting, and map',async()=>{
  const app={innerHTML:''};
  const toast={textContent:'',classList:{add(){},remove(){}}};
  let scrolls=0;
  const values=new Map();
  const events={};
  const route={id:'r',title:'27 Eylül dağıtımı',createdAt:new Date().toISOString(),start:{address:'Bursa merkez',lat:40.195,lng:29.06},end:null,stops:[{id:'s1',company:'Sawinmak',address:'Yücel Cd, Bursa',lat:40.2,lng:29.07,status:'pending',count:1},{id:'s2',company:'Penmak',address:'Kuleler Cd, Bursa',lat:40.21,lng:29.08,status:'pending',count:2}]};
  const finished={id:'finished',title:'Eski rota',createdAt:new Date().toISOString(),finishedAt:new Date().toISOString(),start:{address:'Bursa merkez',lat:40.195,lng:29.06},end:{address:'Eski depo',lat:40.18,lng:29.04},stops:[]};
  const bookEntry={id:'business',company:'Bursa İşletmesi',address:'Nilüfer, Bursa',lat:40.18,lng:29.03,parcel:'ESKİ',count:4,notes:'Eski teslimat notu'};
  const cloudWrites=[];
  estimateLocally(route);
  globalThis.localStorage={getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key)};
  const fields={'#route-title':{value:'Yeni Bursa rotası'},'#start-address':{value:'Bursa merkez'},'#end-address':{value:''}};
  globalThis.document={querySelector:selector=>selector==='#app'?app:selector==='#toast'?toast:fields[selector]||null,addEventListener:(type,handler)=>{(events[type]??=[]).push(handler)}};
  globalThis.window={scrollTo:()=>{scrolls++},addEventListener:()=>{}};
  globalThis.fetch=async(url,options={})=>{
    if(url==='/api/sync'&&options.method==='PUT')cloudWrites.push(JSON.parse(options.body).data);
    const result=url==='/api/config'?{mode:'demo',syncEnabled:true}
      :url==='/api/session'?{user:{id:'owner',email:'owner@example.com'}}
      :{revision:1,data:{routes:[route,finished],addressBook:[bookEntry],activeId:'r'}};
    return {ok:true,json:async()=>result};
  };
  const interval=globalThis.setInterval;
  globalThis.setInterval=()=>0;
  try{
    await import('../public/app.js');
    await new Promise(resolve=>setTimeout(resolve,30));
    assert.match(app.innerHTML,/Bugün nereye/);
    assert.equal(scrolls,1);
    const click=async(action,extra={})=>events.click[0]({target:{closest:selector=>selector==='.stopactions'?null:{dataset:{action,...extra}}},preventDefault:()=>{}});
    await click('screen',{screen:'route'});
    assert.match(app.innerHTML,/SIRADAKİ DURAK/);
    assert.match(app.innerHTML,/Sawinmak/);
    assert.match(app.innerHTML,/<a class="primary maps-link" href="https:\/\/www\.google\.com\/maps\/dir\/\?api=1&amp;destination=40\.2%2C29\.07[^\"]*"[^>]*>Navigasyonu aç ↗<\/a>/);
    assert.doesNotMatch(app.innerHTML,/data-action="navigate(?:-next)?"|CANLI ROTA TAKİBİ/);
    assert.match(app.innerHTML,/İşlemler ⋯/);
    assert.doesNotMatch(app.innerHTML,/Rotayı optimize et/);
    assert.doesNotMatch(app.innerHTML,/id="quick-company"/);
    assert.doesNotMatch(app.innerHTML,/class="detail"/);
    await click('toggle-tools');
    assert.match(app.innerHTML,/Rotayı optimize et/);
    assert.match(app.innerHTML,/id="quick-company"/);
    await click('select',{id:'s2'});
    assert.match(app.innerHTML,/SEÇİLİ DURAK/);
    await click('close-detail');
    assert.doesNotMatch(app.innerHTML,/SEÇİLİ DURAK/);
    assert.match(app.innerHTML,/data-action="toggle-sort"/);
    assert.doesNotMatch(app.innerHTML,/data-action="move"/);
    await click('toggle-sort');
    assert.match(app.innerHTML,/data-action="move"/);
    await click('set-view',{view:'map'});
    assert.match(app.innerHTML,/Şematik görünüm/);
    assert.doesNotMatch(app.innerHTML,/data-action="new"/);
    await click('new');
    assert.match(app.innerHTML,/Önce açık rotayı bitir/);
    await click('save-route');
    await click('demo');
    assert.equal(JSON.parse(values.get('kargo.routes.v1'))?.routes.length??2,2);
    globalThis.confirm=()=>true;
    await click('finish');
    assert.equal(route.finishedAt,undefined);
    assert.match(app.innerHTML,/bekleyen durakları/);
    await click('screen',{screen:'settings'});
    fields['#return-address']={value:'Bursa merkez'};
    await click('save-return');
    const withReturn=JSON.parse(values.get('kargo.routes.v1'));
    assert.equal(withReturn.returnAddress.address,'Bursa merkez');
    assert.ok(withReturn.routes.filter(x=>!x.finishedAt).every(x=>x.end?.address==='Bursa merkez'));
    assert.equal(withReturn.routes.find(x=>x.id==='finished').end.address,'Eski depo');
    assert.equal(withReturn.routes.find(x=>x.id==='r').stops[0].status,'pending');
    await click('screen',{screen:'route'});
    assert.match(app.innerHTML,/Dönüş durağı/);
    assert.match(app.innerHTML,/Son durak, dönüş, Bursa merkez/);
    assert.doesNotMatch(app.innerHTML,/Ortak dönüş/);
    await click('deliver-next');
    assert.equal(route.stops[0].status,'delivered');
    await click('delivered');
    assert.equal(route.stops[1].status,'delivered');
    assert.match(app.innerHTML,/SON DURAK · DÖNÜŞ/);
    assert.match(app.innerHTML,/Varış/);
    await click('finish');
    assert.equal(route.finishedAt,undefined);
    assert.match(app.innerHTML,/Önce dönüş durağına varışı işaretle/);
    await click('arrive-return');
    assert.ok(route.returnReachedAt);
    await click('finish');
    assert.ok(route.finishedAt);
    await click('open-history',{id:'r'});
    assert.doesNotMatch(app.innerHTML,/data-action="edit-stop"|data-action="deliver-next"|data-action="toggle-tools"/);
    await click('new');
    assert.match(app.innerHTML,/SON DURAK · DÖNÜŞ/);
    await click('save-route');
    const third=JSON.parse(values.get('kargo.routes.v1'));
    assert.equal(third.routes.length,3);
    assert.equal(third.routes.at(-1).end.address,'Bursa merkez');
    await click('screen',{screen:'home'});
    await click('quick-address');
    const quick=JSON.parse(values.get('kargo.routes.v1'));
    assert.equal(quick.routes.length,3);
    assert.equal(quick.routes.at(-1).end.address,'Bursa merkez');
    await click('screen',{screen:'book'});
    await click('book-favorite',{id:'business'});
    assert.match(app.innerHTML,/★ Favoriler/);
    assert.equal(JSON.parse(values.get('kargo.routes.v1')).addressBook[0].favorite,true);
    await click('book-remove',{id:'business'});
    assert.doesNotMatch(app.innerHTML,/Bursa İşletmesi rotaya ekle/);
    assert.match(app.innerHTML,/data-action="book-undo"/);
    assert.ok(JSON.parse(values.get('kargo.routes.v1')).deletedAddressIds.includes('business'));
    await click('book-undo');
    assert.match(app.innerHTML,/Bursa İşletmesi rotaya ekle/);
    const restored=JSON.parse(values.get('kargo.routes.v1')).addressBook.find(x=>x.company==='Bursa İşletmesi');
    assert.ok(restored&&restored.id!=='business');
    await click('book-add',{id:restored.id});
    const lastStop=JSON.parse(values.get('kargo.routes.v1')).routes.at(-1).stops.at(-1);
    assert.equal(lastStop.parcel,'');
    assert.equal(lastStop.count,1);
    assert.equal(lastStop.notes,'');
    await new Promise(resolve=>setTimeout(resolve,700));
    assert.equal(cloudWrites.at(-1).returnAddress.address,'Bursa merkez');
  }finally{globalThis.setInterval=interval;clearTimeout(globalThis.window.toastTimer)}
});
